server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      # discovery:
      #   locator:
      #     enabled: true
      #     lower-case-service-id: true
      routes:
        - id: aplicativo_movie-service
          uri: lb://movie-service
          predicates:
            - Path=/api/movies/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: moviesService
                fallbackUri: forward:/fallback/movies
        - id: aplicativo_serie-service
          uri: lb://serie-service
          predicates:
            - Path=/api/series/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: seriesService
                fallbackUri: forward:/fallback/series
                
        - id: aplicativo_catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/api/catalog/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalog

queue:
  movie:
    name: MovieQueue
  serie:
    name: SerieQueue

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true
        

info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway  